services:
  api:
    build: ./backend        
    ports:
      - "9006:9002"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:9002"

  web:
    build: ./frontend
    ports:
      - "3006:5173"
    volumes:
      - ./frontend:/frontend
    
