services:
  api:
    build: ./backend        
    ports:
      - "9006:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./frontend
    ports:
      - "3006:3000"
    volumes:
      - ./frontend:/frontend
